language: python

# ==== LINUX ====
dist: focal
python: 3.8

# ==== WIN32 ====
matrix:
  include:
    - name: "Python 3.8 on Windows"
      os: windows
      language: shell
      before-install:
        - choco install python --version 3.8.5
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

before-install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - pip install -r requirements.txt
script: pytest
