# Classic theme

GUI:
  QMenuBar:
    background-color: FFFFFF
    color: 000000
    spacing: 5
    selected: a8a8a8

  QMenuBarItem:
    background-color: FFFFFF
    color: 000000
    padding: 15
    selected: a8a8a8

  QPlainTextEdit:
    background-color: FFFFFF
    border: 000000
    color: 000000

  QMainWindow:
    background-color: FFFFFF

Editor:
  error: FF312E