cursor_width: 7
editor_font: Consolas
editor_size: 20
init_x: 100
init_y: 100
live_fill: split
live_quality: 150
live_thread_refresh: 0.3
live_update: 0.5
menu_bar_font: Segoe UI
menu_bar_size: 11
min_ratio: 0.7
screen_ratio: 0.9
theme: dark
window_title: ABUELA
