# Settings File

# The title of the GUI's window
# CONSIDER ADDING [BETA] IF NECESSARY
window_title: ABUELA

# The selected theme for the GUI window
theme: default

# The ratio of the window resolution to the screen resolution
screen_ratio: 0.9

# The ratio of the minimal window resolution to the screen resolution
min_ratio: 0.7

# The initial coordinates of the GUI window
init_x: 100
init_y: 100

# The editor's font
editor_font: Consolas

# The editor's font size
editor_size: 20

# The editor's cursor width
cursor_width: 7

# The fill mode of the live-compiled image
# Fill the screen: fill, stretch
# Keep the ratio: fit, a4
# Split the screen: split, center
live_fill: fit

# The quality of the live-compiled image
live_quality: 90

# The quality of a saved image
compile_quality: 700

# The delay to wait for a new edit
live_await: 0.5

# The delay (seconds) for the live-compiled update to occur
# Not recommended to go under 0.5
live_update: 0.5

# The time (seconds) between each time a compiler thread checks if it's time to execute
live_thread_refresh: 0.3

# The text font to display for all menu elements
menu_font: Segoe UI

# The text font size to display for menu bar elements
menu_bar_size: 11

# The text font size to display for status bar elements
status_bar_size: 9

# The space between 2 adjacent Status Bar items
status_margin: 10

# The space between a Status Bar item key to it's value
status_spacing: 5
