# Settings File

# The title of the GUI's window
window_title: ABUELA

# The selected theme for the GUI window
theme: default

# The ratio of the window resolution to the screen resolution
screen_ratio: 0.9

# The ratio of the minimal window resolution to the screen resolution
min_ratio: 0.7

# The initial coordinates of the GUI window
init_x: 100
init_y: 100

# The editor's font
editor_font: Consolas

# The editor's font size
editor_size: 20

# The editor's cursor width
cursor_width: 7

# The fill mode of the live-compiled image
# Fill the screen: fill, stretch
# Keep the ratio: fit, a4
# Split the screen: split, center
live_fill: fit

# The quality of the live-compiled image
live_quality: 150

# The speed (seconds) for the live-compiled update to occur
# Not recommended to go under the live_thread_refresh time
live_update: 0.5

# The speed (seconds) for each compiler thread to check for a new character
# Not recommended to go under 0.3
live_thread_refresh: 0.3

# The text font to display for all menu elements
menu_bar_font: Segoe UI

# The text font size to display for menu bar elements
menu_bar_size: 11